[package]
name = "analytics"
version = "0.1.0"
authors = ["Saurabh Raje <saurabh.mraje@gmail.com>"]

[dependencies]
grouille={path="../grouille"}
rayon="*"
rayon_adaptive={path="../rayon-adaptive"}
itertools="*"
rand="*"
