[package]
name = "analytics"
version = "0.1.0"
authors = ["Saurabh Raje <saurabh.mraje@gmail.com>"]
[profile.release]
debug = true
[dev-dependencies]
criterion="*"
[dependencies]
time = "*"
grouille={path="../grouille"}
rayon="*"
rayon_adaptive={path="../rayon-adaptive"}
itertools="*"
rand="*"
rayon_logs={path="../rayon-logs"}
[[bench]]
name ="insitu_analytics"
path = "benches/insitu_analytics.rs"
harness = false
